/**
 * ML Algorithm node definitions
 * Includes regression and classification algorithms
 */

import type { NodeCategory } from "./nodeDefinitions";
import { Brain } from "lucide-react";

export const mlAlgorithmsCategory: NodeCategory = {
  id: "ml-algorithms",
  label: "ML Algorithms",
  icon: Brain,
  nodes: [
    // Regression Algorithms
    {
      type: "linear_regression",
      label: "Linear Regression",
      description: "Train linear regression model for continuous predictions",
      category: "ml-algorithms",
      icon: Brain,
      color: "#3B82F6",
      defaultConfig: {
        train_dataset_id: "",
        target_column: "",
        fit_intercept: true,
      },
      configFields: [
        {
          name: "train_dataset_id",
          label: "Training Dataset",
          type: "text",
          required: true,
          autoFill: true,
          description: "Auto-filled from connected split node",
        },
        {
          name: "fit_intercept",
          label: "Fit Intercept",
          type: "checkbox",
          defaultValue: true,
          description: "Calculate intercept for the model",
        },
      ],
    },

    // Classification Algorithms
    {
      type: "logistic_regression",
      label: "Logistic Regression",
      description:
        "Train logistic regression for binary/multi-class classification",
      category: "ml-algorithms",
      icon: Brain,
      color: "#8B5CF6",
      defaultConfig: {
        train_dataset_id: "",
        fit_intercept: true,
        show_advanced_options: false,
        // Advanced options with sensible defaults
        C: 1.0,
        penalty: "l2",
        solver: "lbfgs",
        max_iter: 1000,
        random_state: 42,
      },
      configFields: [
        {
          name: "train_dataset_id",
          label: "Training Dataset",
          type: "text",
          required: true,
          autoFill: true,
          description: "Auto-filled from connected split node",
        },
        {
          name: "fit_intercept",
          label: "Fit Intercept",
          type: "checkbox",
          defaultValue: true,
          description: "Calculate intercept for the model",
        },
        {
          name: "show_advanced_options",
          label: "Show Advanced Options",
          type: "checkbox",
          defaultValue: false,
          description: "Toggle to show/hide advanced hyperparameters",
        },
        // Advanced hyperparameters (only shown when show_advanced_options is true)
        {
          name: "C",
          label: "Regularization Strength (C)",
          type: "number",
          required: false,
          defaultValue: 1.0,
          min: 0.001,
          max: 100,
          step: 0.1,
          description:
            "Inverse of regularization strength (smaller = stronger regularization)",
          conditionalDisplay: { field: "show_advanced_options", equals: true },
        },
        {
          name: "penalty",
          label: "Penalty Type",
          type: "select",
          required: false,
          options: [
            { value: "l2", label: "L2 (Ridge)" },
            { value: "l1", label: "L1 (Lasso)" },
            { value: "none", label: "None" },
          ],
          defaultValue: "l2",
          description: "Regularization penalty type",
          conditionalDisplay: { field: "show_advanced_options", equals: true },
        },
        {
          name: "solver",
          label: "Solver",
          type: "select",
          required: false,
          options: [
            { value: "lbfgs", label: "LBFGS (recommended)" },
            { value: "liblinear", label: "Liblinear" },
            { value: "saga", label: "SAGA" },
            { value: "newton-cg", label: "Newton-CG" },
          ],
          defaultValue: "lbfgs",
          description: "Optimization algorithm",
          conditionalDisplay: { field: "show_advanced_options", equals: true },
        },
        {
          name: "max_iter",
          label: "Max Iterations",
          type: "number",
          required: false,
          defaultValue: 1000,
          min: 100,
          max: 10000,
          description: "Maximum iterations for convergence",
          conditionalDisplay: { field: "show_advanced_options", equals: true },
        },
        {
          name: "random_state",
          label: "Random State",
          type: "number",
          required: false,
          defaultValue: 42,
          description: "Seed for reproducibility",
          conditionalDisplay: { field: "show_advanced_options", equals: true },
        },
      ],
    },

    {
      type: "decision_tree",
      label: "Decision Tree",
      description: "Train decision tree for classification or regression",
      category: "ml-algorithms",
      icon: Brain,
      color: "#10B981",
      defaultConfig: {
        train_dataset_id: "",
        task_type: "classification",
        max_depth: null,
        min_samples_split: 2,
        min_samples_leaf: 1,
        random_state: 42,
      },
      configFields: [
        {
          name: "train_dataset_id",
          label: "Training Dataset",
          type: "text",
          required: true,
          autoFill: true,
          description: "Connect to train output from split node",
        },
        {
          name: "target_column",
          label: "Target Column",
          type: "select",
          required: true,
          autoFill: true,
          description: "Column to predict",
        },
        {
          name: "task_type",
          label: "Task Type",
          type: "select",
          options: [
            { value: "classification", label: "Classification" },
            { value: "regression", label: "Regression" },
          ],
          defaultValue: "classification",
          description: "Type of prediction task",
        },
        {
          name: "max_depth",
          label: "Max Depth",
          type: "number",
          defaultValue: null,
          min: 1,
          max: 50,
          description: "Maximum tree depth (null = unlimited)",
        },
        {
          name: "min_samples_split",
          label: "Min Samples to Split",
          type: "number",
          defaultValue: 2,
          min: 2,
          max: 100,
          description: "Minimum samples required to split a node",
        },
        {
          name: "min_samples_leaf",
          label: "Min Samples per Leaf",
          type: "number",
          defaultValue: 1,
          min: 1,
          max: 50,
          description: "Minimum samples required in a leaf node",
        },
        {
          name: "random_state",
          label: "Random State",
          type: "number",
          defaultValue: 42,
          description: "Seed for reproducibility",
        },
      ],
    },

    {
      type: "random_forest",
      label: "Random Forest",
      description:
        "Train random forest ensemble for classification or regression",
      category: "ml-algorithms",
      icon: Brain,
      color: "#F59E0B",
      defaultConfig: {
        train_dataset_id: "",
        task_type: "classification",
        n_estimators: 100,
        max_depth: null,
        min_samples_split: 2,
        min_samples_leaf: 1,
        random_state: 42,
      },
      configFields: [
        {
          name: "train_dataset_id",
          label: "Training Dataset",
          type: "text",
          required: true,
          autoFill: true,
          description: "Connect to train output from split node",
        },
        {
          name: "target_column",
          label: "Target Column",
          type: "select",
          required: true,
          autoFill: true,
          description: "Column to predict",
        },
        {
          name: "task_type",
          label: "Task Type",
          type: "select",
          options: [
            { value: "classification", label: "Classification" },
            { value: "regression", label: "Regression" },
          ],
          defaultValue: "classification",
          description: "Type of prediction task",
        },
        {
          name: "n_estimators",
          label: "Number of Trees",
          type: "number",
          defaultValue: 100,
          min: 10,
          max: 1000,
          description: "Number of trees in the forest",
        },
        {
          name: "max_depth",
          label: "Max Depth",
          type: "number",
          defaultValue: null,
          min: 1,
          max: 50,
          description: "Maximum tree depth (null = unlimited)",
        },
        {
          name: "min_samples_split",
          label: "Min Samples to Split",
          type: "number",
          defaultValue: 2,
          min: 2,
          max: 100,
          description: "Minimum samples required to split a node",
        },
        {
          name: "min_samples_leaf",
          label: "Min Samples per Leaf",
          type: "number",
          defaultValue: 1,
          min: 1,
          max: 50,
          description: "Minimum samples required in a leaf node",
        },
        {
          name: "random_state",
          label: "Random State",
          type: "number",
          defaultValue: 42,
          description: "Seed for reproducibility",
        },
      ],
    },
  ],
};
