"""update schema

Revision ID: b5d726af7c5c
Revises: 
Create Date: 2026-01-21 09:46:48.021836

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b5d726af7c5c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('STUDENT', 'ADMIN', name='userrole'), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('isActive', sa.Boolean(), nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.Column('updatedAt', sa.DateTime(), nullable=False),
    sa.Column('lastLogin', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admins_email'), 'admins', ['email'], unique=True)
    op.create_index(op.f('ix_admins_id'), 'admins', ['id'], unique=False)
    op.create_table('students',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('emailId', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.Column('role', sa.Enum('STUDENT', 'ADMIN', name='userrole'), nullable=False),
    sa.Column('authProvider', sa.Enum('LOCAL', 'GOOGLE', name='authprovider'), nullable=False),
    sa.Column('googleId', sa.String(length=255), nullable=True),
    sa.Column('collegeOrSchool', sa.String(length=255), nullable=True),
    sa.Column('contactNo', sa.String(length=20), nullable=True),
    sa.Column('recentProject', sa.Text(), nullable=True),
    sa.Column('profilePic', sa.String(length=500), nullable=True),
    sa.Column('isPremium', sa.Boolean(), nullable=False),
    sa.Column('isActive', sa.Boolean(), nullable=False),
    sa.Column('resetToken', sa.String(length=255), nullable=True),
    sa.Column('resetTokenExpiry', sa.DateTime(), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.Column('updatedAt', sa.DateTime(), nullable=False),
    sa.Column('lastLogin', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_students_emailId'), 'students', ['emailId'], unique=True)
    op.create_index(op.f('ix_students_googleId'), 'students', ['googleId'], unique=True)
    op.create_index(op.f('ix_students_id'), 'students', ['id'], unique=False)
    op.create_table('api_secrets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('studentId', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('encryptedKey', sa.Text(), nullable=False),
    sa.Column('keyHash', sa.String(length=255), nullable=False),
    sa.Column('isActive', sa.Boolean(), nullable=False),
    sa.Column('lastUsedAt', sa.DateTime(), nullable=True),
    sa.Column('usageCount', sa.Integer(), nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.Column('updatedAt', sa.DateTime(), nullable=False),
    sa.Column('expiresAt', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['studentId'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_secrets_id'), 'api_secrets', ['id'], unique=False)
    op.create_index(op.f('ix_api_secrets_keyHash'), 'api_secrets', ['keyHash'], unique=True)
    op.create_index(op.f('ix_api_secrets_provider'), 'api_secrets', ['provider'], unique=False)
    op.create_index(op.f('ix_api_secrets_studentId'), 'api_secrets', ['studentId'], unique=False)
    op.create_table('genai_pipelines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('pipelineType', sa.Enum('CLASSIC_ML', 'GENAI', 'HYBRID', name='pipelinetype'), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'ACTIVE', 'ARCHIVED', name='pipelinestatus'), nullable=False),
    sa.Column('studentId', sa.Integer(), nullable=False),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('isTemplate', sa.Boolean(), nullable=False),
    sa.Column('templateId', sa.Integer(), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.Column('updatedAt', sa.DateTime(), nullable=False),
    sa.Column('lastRunAt', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['studentId'], ['students.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['templateId'], ['genai_pipelines.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_genai_pipelines_createdAt'), 'genai_pipelines', ['createdAt'], unique=False)
    op.create_index(op.f('ix_genai_pipelines_id'), 'genai_pipelines', ['id'], unique=False)
    op.create_index(op.f('ix_genai_pipelines_studentId'), 'genai_pipelines', ['studentId'], unique=False)
    op.create_table('knowledge_bases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('studentId', sa.Integer(), nullable=False),
    sa.Column('embeddingModel', sa.String(length=100), nullable=False),
    sa.Column('chunkSize', sa.Integer(), nullable=False),
    sa.Column('chunkOverlap', sa.Integer(), nullable=False),
    sa.Column('vectorStore', sa.String(length=50), nullable=False),
    sa.Column('totalDocuments', sa.Integer(), nullable=False),
    sa.Column('totalChunks', sa.Integer(), nullable=False),
    sa.Column('indexedAt', sa.DateTime(), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.Column('updatedAt', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['studentId'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_bases_createdAt'), 'knowledge_bases', ['createdAt'], unique=False)
    op.create_index(op.f('ix_knowledge_bases_id'), 'knowledge_bases', ['id'], unique=False)
    op.create_index(op.f('ix_knowledge_bases_studentId'), 'knowledge_bases', ['studentId'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=500), nullable=False),
    sa.Column('expiresAt', sa.DateTime(), nullable=False),
    sa.Column('isRevoked', sa.Boolean(), nullable=False),
    sa.Column('studentId', sa.Integer(), nullable=True),
    sa.Column('adminId', sa.Integer(), nullable=True),
    sa.Column('deviceInfo', sa.String(length=255), nullable=True),
    sa.Column('ipAddress', sa.String(length=45), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.Column('usedAt', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['adminId'], ['admins.id'], ),
    sa.ForeignKeyConstraint(['studentId'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refresh_tokens_id'), 'refresh_tokens', ['id'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_token'), 'refresh_tokens', ['token'], unique=True)
    op.create_table('conversation_memory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sessionId', sa.String(length=255), nullable=False),
    sa.Column('studentId', sa.Integer(), nullable=False),
    sa.Column('pipelineId', sa.Integer(), nullable=True),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('messageMetadata', sa.JSON(), nullable=True),
    sa.Column('turnIndex', sa.Integer(), nullable=False),
    sa.Column('isSummarized', sa.Boolean(), nullable=False),
    sa.Column('summaryId', sa.Integer(), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['pipelineId'], ['genai_pipelines.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['studentId'], ['students.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['summaryId'], ['conversation_memory.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversation_memory_createdAt'), 'conversation_memory', ['createdAt'], unique=False)
    op.create_index(op.f('ix_conversation_memory_id'), 'conversation_memory', ['id'], unique=False)
    op.create_index(op.f('ix_conversation_memory_pipelineId'), 'conversation_memory', ['pipelineId'], unique=False)
    op.create_index(op.f('ix_conversation_memory_sessionId'), 'conversation_memory', ['sessionId'], unique=False)
    op.create_index(op.f('ix_conversation_memory_studentId'), 'conversation_memory', ['studentId'], unique=False)
    op.create_table('genai_nodes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pipelineId', sa.Integer(), nullable=False),
    sa.Column('nodeType', sa.String(length=100), nullable=False),
    sa.Column('nodeId', sa.String(length=255), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=True),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('positionX', sa.Float(), nullable=True),
    sa.Column('positionY', sa.Float(), nullable=True),
    sa.Column('isEnabled', sa.Boolean(), nullable=False),
    sa.Column('executionOrder', sa.Integer(), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.Column('updatedAt', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['pipelineId'], ['genai_pipelines.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_genai_nodes_id'), 'genai_nodes', ['id'], unique=False)
    op.create_index(op.f('ix_genai_nodes_nodeId'), 'genai_nodes', ['nodeId'], unique=True)
    op.create_index(op.f('ix_genai_nodes_nodeType'), 'genai_nodes', ['nodeType'], unique=False)
    op.create_index(op.f('ix_genai_nodes_pipelineId'), 'genai_nodes', ['pipelineId'], unique=False)
    op.create_table('kb_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kbId', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=500), nullable=False),
    sa.Column('fileType', sa.String(length=50), nullable=True),
    sa.Column('fileSize', sa.Integer(), nullable=True),
    sa.Column('filePath', sa.String(length=1000), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('documentMetadata', sa.JSON(), nullable=True),
    sa.Column('totalChunks', sa.Integer(), nullable=False),
    sa.Column('isIndexed', sa.Boolean(), nullable=False),
    sa.Column('uploadedAt', sa.DateTime(), nullable=False),
    sa.Column('indexedAt', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['kbId'], ['knowledge_bases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kb_documents_id'), 'kb_documents', ['id'], unique=False)
    op.create_index(op.f('ix_kb_documents_kbId'), 'kb_documents', ['kbId'], unique=False)
    op.create_table('document_chunks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('documentId', sa.Integer(), nullable=False),
    sa.Column('chunkIndex', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('embedding', sa.JSON(), nullable=True),
    sa.Column('embeddingModel', sa.String(length=100), nullable=True),
    sa.Column('startChar', sa.Integer(), nullable=True),
    sa.Column('endChar', sa.Integer(), nullable=True),
    sa.Column('tokenCount', sa.Integer(), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['documentId'], ['kb_documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_chunks_documentId'), 'document_chunks', ['documentId'], unique=False)
    op.create_index(op.f('ix_document_chunks_id'), 'document_chunks', ['id'], unique=False)
    op.create_table('genai_edges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pipelineId', sa.Integer(), nullable=False),
    sa.Column('sourceNodeId', sa.Integer(), nullable=False),
    sa.Column('targetNodeId', sa.Integer(), nullable=False),
    sa.Column('sourceHandle', sa.String(length=50), nullable=True),
    sa.Column('targetHandle', sa.String(length=50), nullable=True),
    sa.Column('label', sa.String(length=255), nullable=True),
    sa.Column('condition', sa.JSON(), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.Column('updatedAt', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['pipelineId'], ['genai_pipelines.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sourceNodeId'], ['genai_nodes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['targetNodeId'], ['genai_nodes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_genai_edges_id'), 'genai_edges', ['id'], unique=False)
    op.create_index(op.f('ix_genai_edges_pipelineId'), 'genai_edges', ['pipelineId'], unique=False)
    op.create_index(op.f('ix_genai_edges_sourceNodeId'), 'genai_edges', ['sourceNodeId'], unique=False)
    op.create_index(op.f('ix_genai_edges_targetNodeId'), 'genai_edges', ['targetNodeId'], unique=False)
    op.create_table('genai_pipeline_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('runId', sa.String(length=255), nullable=False),
    sa.Column('pipelineId', sa.Integer(), nullable=False),
    sa.Column('studentId', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', 'CANCELLED', 'PAUSED', name='runstatus'), nullable=False),
    sa.Column('startNodeId', sa.Integer(), nullable=True),
    sa.Column('inputData', sa.JSON(), nullable=True),
    sa.Column('finalOutput', sa.JSON(), nullable=True),
    sa.Column('totalTokensUsed', sa.Integer(), nullable=False),
    sa.Column('totalCostUSD', sa.Float(), nullable=False),
    sa.Column('executionTimeMs', sa.Integer(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('errorStack', sa.Text(), nullable=True),
    sa.Column('startedAt', sa.DateTime(), nullable=True),
    sa.Column('completedAt', sa.DateTime(), nullable=True),
    sa.Column('cancelledAt', sa.DateTime(), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['pipelineId'], ['genai_pipelines.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['startNodeId'], ['genai_nodes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['studentId'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_genai_pipeline_runs_id'), 'genai_pipeline_runs', ['id'], unique=False)
    op.create_index(op.f('ix_genai_pipeline_runs_pipelineId'), 'genai_pipeline_runs', ['pipelineId'], unique=False)
    op.create_index(op.f('ix_genai_pipeline_runs_runId'), 'genai_pipeline_runs', ['runId'], unique=True)
    op.create_index(op.f('ix_genai_pipeline_runs_startedAt'), 'genai_pipeline_runs', ['startedAt'], unique=False)
    op.create_index(op.f('ix_genai_pipeline_runs_status'), 'genai_pipeline_runs', ['status'], unique=False)
    op.create_index(op.f('ix_genai_pipeline_runs_studentId'), 'genai_pipeline_runs', ['studentId'], unique=False)
    op.create_table('genai_node_executions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('runId', sa.Integer(), nullable=False),
    sa.Column('nodeId', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', 'CANCELLED', 'PAUSED', name='runstatus'), nullable=False),
    sa.Column('inputData', sa.JSON(), nullable=True),
    sa.Column('outputData', sa.JSON(), nullable=True),
    sa.Column('tokensUsed', sa.Integer(), nullable=True),
    sa.Column('costUSD', sa.Float(), nullable=True),
    sa.Column('executionTimeMs', sa.Integer(), nullable=True),
    sa.Column('provider', sa.String(length=50), nullable=True),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('retryCount', sa.Integer(), nullable=False),
    sa.Column('startedAt', sa.DateTime(), nullable=True),
    sa.Column('completedAt', sa.DateTime(), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['nodeId'], ['genai_nodes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['runId'], ['genai_pipeline_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_genai_node_executions_id'), 'genai_node_executions', ['id'], unique=False)
    op.create_index(op.f('ix_genai_node_executions_nodeId'), 'genai_node_executions', ['nodeId'], unique=False)
    op.create_index(op.f('ix_genai_node_executions_runId'), 'genai_node_executions', ['runId'], unique=False)
    op.drop_table('playing_with_neon')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('playing_with_neon',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('value', sa.REAL(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('playing_with_neon_pkey'))
    )
    op.drop_index(op.f('ix_genai_node_executions_runId'), table_name='genai_node_executions')
    op.drop_index(op.f('ix_genai_node_executions_nodeId'), table_name='genai_node_executions')
    op.drop_index(op.f('ix_genai_node_executions_id'), table_name='genai_node_executions')
    op.drop_table('genai_node_executions')
    op.drop_index(op.f('ix_genai_pipeline_runs_studentId'), table_name='genai_pipeline_runs')
    op.drop_index(op.f('ix_genai_pipeline_runs_status'), table_name='genai_pipeline_runs')
    op.drop_index(op.f('ix_genai_pipeline_runs_startedAt'), table_name='genai_pipeline_runs')
    op.drop_index(op.f('ix_genai_pipeline_runs_runId'), table_name='genai_pipeline_runs')
    op.drop_index(op.f('ix_genai_pipeline_runs_pipelineId'), table_name='genai_pipeline_runs')
    op.drop_index(op.f('ix_genai_pipeline_runs_id'), table_name='genai_pipeline_runs')
    op.drop_table('genai_pipeline_runs')
    op.drop_index(op.f('ix_genai_edges_targetNodeId'), table_name='genai_edges')
    op.drop_index(op.f('ix_genai_edges_sourceNodeId'), table_name='genai_edges')
    op.drop_index(op.f('ix_genai_edges_pipelineId'), table_name='genai_edges')
    op.drop_index(op.f('ix_genai_edges_id'), table_name='genai_edges')
    op.drop_table('genai_edges')
    op.drop_index(op.f('ix_document_chunks_id'), table_name='document_chunks')
    op.drop_index(op.f('ix_document_chunks_documentId'), table_name='document_chunks')
    op.drop_table('document_chunks')
    op.drop_index(op.f('ix_kb_documents_kbId'), table_name='kb_documents')
    op.drop_index(op.f('ix_kb_documents_id'), table_name='kb_documents')
    op.drop_table('kb_documents')
    op.drop_index(op.f('ix_genai_nodes_pipelineId'), table_name='genai_nodes')
    op.drop_index(op.f('ix_genai_nodes_nodeType'), table_name='genai_nodes')
    op.drop_index(op.f('ix_genai_nodes_nodeId'), table_name='genai_nodes')
    op.drop_index(op.f('ix_genai_nodes_id'), table_name='genai_nodes')
    op.drop_table('genai_nodes')
    op.drop_index(op.f('ix_conversation_memory_studentId'), table_name='conversation_memory')
    op.drop_index(op.f('ix_conversation_memory_sessionId'), table_name='conversation_memory')
    op.drop_index(op.f('ix_conversation_memory_pipelineId'), table_name='conversation_memory')
    op.drop_index(op.f('ix_conversation_memory_id'), table_name='conversation_memory')
    op.drop_index(op.f('ix_conversation_memory_createdAt'), table_name='conversation_memory')
    op.drop_table('conversation_memory')
    op.drop_index(op.f('ix_refresh_tokens_token'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_id'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_knowledge_bases_studentId'), table_name='knowledge_bases')
    op.drop_index(op.f('ix_knowledge_bases_id'), table_name='knowledge_bases')
    op.drop_index(op.f('ix_knowledge_bases_createdAt'), table_name='knowledge_bases')
    op.drop_table('knowledge_bases')
    op.drop_index(op.f('ix_genai_pipelines_studentId'), table_name='genai_pipelines')
    op.drop_index(op.f('ix_genai_pipelines_id'), table_name='genai_pipelines')
    op.drop_index(op.f('ix_genai_pipelines_createdAt'), table_name='genai_pipelines')
    op.drop_table('genai_pipelines')
    op.drop_index(op.f('ix_api_secrets_studentId'), table_name='api_secrets')
    op.drop_index(op.f('ix_api_secrets_provider'), table_name='api_secrets')
    op.drop_index(op.f('ix_api_secrets_keyHash'), table_name='api_secrets')
    op.drop_index(op.f('ix_api_secrets_id'), table_name='api_secrets')
    op.drop_table('api_secrets')
    op.drop_index(op.f('ix_students_id'), table_name='students')
    op.drop_index(op.f('ix_students_googleId'), table_name='students')
    op.drop_index(op.f('ix_students_emailId'), table_name='students')
    op.drop_table('students')
    op.drop_index(op.f('ix_admins_id'), table_name='admins')
    op.drop_index(op.f('ix_admins_email'), table_name='admins')
    op.drop_table('admins')
    # ### end Alembic commands ###
