"""add_email_verification_fields

Revision ID: 6c828d0aa2fd
Revises: 284a03fdedc4
Create Date: 2026-01-22 12:02:05.702366

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
"""add_email_verification_fields

Revision ID: 6c828d0aa2fd
Revises: 284a03fdedc4
Create Date: 2026-01-22 12:02:05.702366

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c828d0aa2fd'
down_revision: Union[str, None] = '284a03fdedc4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add columns as nullable first with default values
    op.add_column('students', sa.Column('isEmailVerified', sa.Boolean(), nullable=True))
    op.add_column('students', sa.Column('verificationOTP', sa.String(length=6), nullable=True))
    op.add_column('students', sa.Column('otpExpiresAt', sa.DateTime(), nullable=True))
    op.add_column('students', sa.Column('verificationToken', sa.String(length=255), nullable=True))
    
    # Set default value for existing records (mark Google OAuth users as verified)
    op.execute("UPDATE students SET \"isEmailVerified\" = CASE WHEN \"authProvider\" = 'GOOGLE' THEN true ELSE false END WHERE \"isEmailVerified\" IS NULL")
    
    # Now alter the column to NOT NULL
    op.alter_column('students', 'isEmailVerified', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('students', 'verificationToken')
    op.drop_column('students', 'otpExpiresAt')
    op.drop_column('students', 'verificationOTP')
    op.drop_column('students', 'isEmailVerified')
    # ### end Alembic commands ###
